name: ci

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Build
        run: |
          bazel build //...
      
      - name: Test
        run: |
          bazel test //...

      - name: Run examples
        run: |
          # Don't run the example based on binaries for now, because the binaries are not
          # available to download.
          EXAMPLES="$(find examples -type d -maxdepth 1 -mindepth 1 | grep -v use-binaries)"
          for f in $EXAMPLES; do
            echo "Running example $f"
            (cd "$f" && bazel run snapshots -- collect)
          done
